#!/usr/bin/env bash
#
# Copyright (c) 2015 Joyent Inc., All rights reserved.
#
# Install Debian 7 into a directory, modify the installation, then tar it up.
#

set -euo pipefail
IFS=$'\n\t'

NAME="Debian 7 LX Brand"
BUILD_DATE=$(date +%Y%m%d)
TARGET="debian-7-lx-${BUILD_DATE}.tar.gz"

usage() {
cat <<EOF

  Usage: $0 -d <chroot> -m <mirror> -u <image docs>
  
  Install and modify Debian in a given directory in a given directory using a given mirror

  Example:
  $0 -d /data/chroot -m http://httpredir.debian.org/debian/ -u https://docs.joyent.com/images/lx-brand-beta

  OPTIONS:
  -d A path to the install directory
  -m A URL for the desired archive mirror
  -u A URL to the image docs [optional]
  -h Show this message

EOF
}

INSTALL_DIR=
MIRROR=
DOCS=

while getopts "hd:m:u:" OPTION
do
  case $OPTION in
    h)
      usage
      exit
      ;;
    d)
      INSTALL_DIR=${OPTARG%/}
      ;;
    m)
      MIRROR=${OPTARG}
      ;;
    u)
      DOCS=${OPTARG}
      ;;
    \?)
      usage
      exit
      ;;
  esac
done

if [[ $# -eq 0 ]]; then
  usage
  exit 1
fi

if [[ ! -e ${INSTALL_DIR} ]] ; then
  echo "Directory $INSTALL_DIR not found"
  exit 1
fi

if [[ -z ${INSTALL_DIR} ]]; then
  echo "Error: missing install directory (-d) value"
  exit 1
fi

if [[ -z ${MIRROR} ]]; then
  echo "Error: missing mirror (-m) value"
  exit 1
fi

if [[ -z ${DOCS} ]]; then
  DOCS="https://docs.joyent.com/images/lx-brand-beta"
fi

echo "==> Installing Debian into $INSTALL_DIR"

if [[ -d $INSTALL_DIR ]]; then
  echo "====> Found previous chroot. Deleting and creating a new one."
  rm -rf $INSTALL_DIR
  mkdir -p $INSTALL_DIR
fi

debootstrap wheezy $INSTALL_DIR $MIRROR
echo "==> Done!"

echo "==> Settting locale to en_US.UTF-8"
chroot $INSTALL_DIR apt-get -y clean
chroot $INSTALL_DIR apt-get -y update
chroot $INSTALL_DIR apt-get -y install locales
echo "en_US.UTF-8 UTF-8" > $INSTALL_DIR/etc/locale.gen
echo "LANG=\"en_US.UTF-8\"" > $INSTALL_DIR/etc/default/locale
chroot $INSTALL_DIR locale-gen

echo "==> Installing packages..."
chroot $INSTALL_DIR apt-get -y install openssh-server vim wget curl less man-db

echo "==> Cleaning up linux-image packages"
chroot $INSTALL_DIR apt-get -y purge linux-image*
chroot $INSTALL_DIR apt-get -y autoremove
chroot $INSTALL_DIR apt-get -y clean


echo "==> Setting TZ to UTC"
rm $INSTALL_DIR/etc/localtime
cp $INSTALL_DIR/usr/share/zoneinfo/UTC $INSTALL_DIR/etc/localtime

echo "==> Disabling PasswordAuthentication"
sed s/PasswordAuthentication\ yes/PasswordAuthentication\ no/ -i $INSTALL_DIR/etc/ssh/sshd_config

echo "==> Creating /etc/motd"
cat << MOTD > $INSTALL_DIR/etc/motd
   __        .                   .
 _|  |_      | .-. .  . .-. :--. |-
|_    _|     ;|   ||  |(.-' |  | |
  |__|   \`--'  \`-' \`;-| \`-' '  ' \`-'
                   /  ;  Instance ($NAME $BUILD_DATE)
                   \`-'   $DOCS

MOTD

echo "==> Creating /etc/product file"
cat << PRODUCT > $INSTALL_DIR/etc/product
Name: Joyent Instance
Image: $NAME $BUILD_DATE
Documentation: $DOCS
Description: $NAME $BUILD_DATE.
PRODUCT

echo "==> Installing Guest tools in $INSTALL_DIR"
chroot $INSTALL_DIR ln -s /native/usr/sbin/mdata-get /usr/sbin/mdata-get
chroot $INSTALL_DIR ln -s /native/usr/sbin/mdata-put /usr/sbin/mdata-put
chroot $INSTALL_DIR ln -s /native/usr/sbin/mdata-delete /usr/sbin/mdata-delete
chroot $INSTALL_DIR ln -s /native/usr/sbin/mdata-list /usr/sbin/mdata-list
cp -r ./guest-tools/usr/share/man/man1/mdata-* $INSTALL_DIR/usr/share/man/man1/
cp ./guest-tools/lib/smartdc/joyent_rc.local $INSTALL_DIR/etc/rc.local

echo "==> Done!"
sleep 1 

echo "==> Saving installation as $TARGET. This may take a few minutes."
tar czf $TARGET --exclude-from=exclude.txt $INSTALL_DIR/

echo "==> Installation complete!"
echo "==> $TARGET"

exit 0
